const app = document.querySelector('#app');
const title = document.querySelector('#page-title');
const fmt = new Intl.NumberFormat('fr-FR');
let world, competitions;

async function api(path, options) { const response = await fetch(`/api${path}`, options); if (!response.ok) throw new Error(await response.text()); return response.json(); }
function setWorld(data){world=data;document.querySelector('#game-date').textContent=new Date(`${data.date}T12:00`).toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'});document.querySelector('#season-label').textContent=`Saison ${data.season}`}
function nav(view){document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.dataset.view===view));}
function table(headers, rows){return `<table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table>`}

async function dashboard(){title.textContent='Vue d’ensemble';nav('dashboard');const tables=await Promise.all(competitions.map(c=>api(`/competitions/${c.id}/classement`)));app.innerHTML=`<div class="grid"><article class="card metric"><span>JOURNÉE</span><b>${world.current_round} / ${world.round_count}</b><span>${world.next_event==='season_complete'?'Saison terminée':'Prochaine échéance : journée'}</span></article><article class="card metric"><span>CLUBS SIMULÉS</span><b>96</b><span>5 championnats européens</span></article><article class="card metric"><span>JOUEURS ACTIFS</span><b>2 880</b><span>30 par club</span></article><article class="card metric"><span>SAISONS ARCHIVÉES</span><b>${world.completed_seasons}</b><span>Historique conservé</span></article>${competitions.map((c,i)=>`<article class="card wide"><div class="section-head"><h2>${c.name}</h2><a class="link" href="#competition/${c.id}">Classement →</a></div>${table(['#','Club','J','BP','BC','Diff.','Pts'],tables[i].slice(0,6).map((r,n)=>`<tr data-club="${r.club_id}"><td class="rank">${n+1}</td><td>${clubName(r.club_id)}</td><td>${r.played}</td><td>${r.goals_for}</td><td>${r.goals_against}</td><td>${r.goal_difference}</td><td><b>${r.points}</b></td></tr>`))}</article>`).join('')}</div>`; bindClubRows();}
let clubCache=new Map(); function clubName(id){return clubCache.get(id)||`Club #${id}`}
function bindClubRows(){document.querySelectorAll('[data-club]').forEach(row=>row.onclick=()=>location.hash=`club/${row.dataset.club}`)}

async function competition(id){const c=competitions.find(x=>x.id==id),[standing,calendar,stats]=await Promise.all([api(`/competitions/${id}/classement`),api(`/competitions/${id}/calendrier?journee=${world.current_round||1}`),api(`/competitions/${id}/statistiques?type=buteurs`)]);title.textContent=c.name;nav('competitions');app.innerHTML=`<div class="grid"><article class="card wide"><h2>Classement</h2>${table(['#','Club','J','V','N','D','BP','BC','Diff.','Pts'],standing.map((r,n)=>`<tr data-club="${r.club_id}"><td class="rank">${n+1}</td><td>${clubName(r.club_id)}</td><td>${r.played}</td><td>${r.wins}</td><td>${r.draws}</td><td>${r.losses}</td><td>${r.goals_for}</td><td>${r.goals_against}</td><td>${r.goal_difference}</td><td><b>${r.points}</b></td></tr>`))}</article><article class="card side"><h2>Meilleurs buteurs</h2>${table(['Joueur','Buts'],stats.slice(0,8).map(s=>`<tr data-player="${s.player_id}"><td>${s.name}</td><td><b>${s.goals}</b></td></tr>`))}</article><article class="card wide"><h2>Journée ${world.current_round||1}</h2>${table(['Date','Domicile','Score','Extérieur'],calendar.map(m=>`<tr data-match="${m.id}"><td>${m.date}</td><td>${clubName(m.home_club_id)}</td><td>${m.result?`${m.result.home_goals} – ${m.result.away_goals}`:'À venir'}</td><td>${clubName(m.away_club_id)}</td></tr>`))}</article></div>`;bindClubRows();document.querySelectorAll('[data-player]').forEach(x=>x.onclick=()=>location.hash=`player/${x.dataset.player}`);document.querySelectorAll('[data-match]').forEach(x=>x.onclick=()=>location.hash=`match/${x.dataset.match}`)}

async function clubs(){title.textContent='Clubs';nav('clubs');const list=await api('/clubs');list.forEach(c=>clubCache.set(c.id,c.name));app.innerHTML=`<div class="section-head"><div><h2 class="panel-title">Clubs</h2><span class="subtle">${fmt.format(list.length)} clubs consultables</span></div></div><div class="filters"><input id="club-search" placeholder="Rechercher un club"></div><div class="card" id="club-table"></div>`;const render=q=>document.querySelector('#club-table').innerHTML=table(['Club','Pays','Statut','Compétition'],list.filter(c=>c.name.toLowerCase().includes(q.toLowerCase())).slice(0,100).map(c=>`<tr data-club="${c.id}"><td><b>${c.name}</b></td><td>${c.nation}</td><td><span class="badge">${c.status}</span></td><td>${competitions.find(x=>x.id===c.competition_id)?.name||'—'}</td></tr>`));render('');document.querySelector('#club-search').oninput=e=>{render(e.target.value);bindClubRows()};bindClubRows()}

async function players(){title.textContent='Joueurs';nav('joueurs');const list=await api('/joueurs');app.innerHTML=`<div class="section-head"><div><h2 class="panel-title">Joueurs actifs</h2><span class="subtle">${fmt.format(list.length)} profils simulés</span></div></div><div class="filters"><select id="position"><option value="">Tous les postes</option>${['GB','DC','DL','DR','MDC','MC','MOC','AILG','AILD','BU'].map(p=>`<option>${p}</option>`).join('')}</select></div><div class="card" id="player-table"></div>`;const render=p=>document.querySelector('#player-table').innerHTML=table(['Joueur','Poste','Club','Niveau'],list.filter(x=>!p||x.position===p).map(x=>`<tr data-player="${x.id}"><td><b>${x.name}</b></td><td>${x.position}</td><td>${clubName(x.club_id)}</td><td>${x.overall}</td></tr>`));render('');document.querySelector('#position').onchange=e=>{render(e.target.value);bindPlayers()};bindPlayers()}
function bindPlayers(){document.querySelectorAll('[data-player]').forEach(x=>x.onclick=()=>location.hash=`player/${x.dataset.player}`)}
async function club(id){const [summary,roster,calendar]=await Promise.all([api(`/clubs/${id}`),api(`/clubs/${id}/effectif`),api(`/clubs/${id}/calendrier`)]);title.textContent=summary.name;app.innerHTML=`<div class="section-head"><div><p class="eyebrow">${summary.status.toUpperCase()}</p><h2 class="panel-title">${summary.name}</h2><span class="subtle">${summary.nation}</span></div></div><div class="grid"><article class="card wide"><h2>Effectif</h2>${table(['Joueur','Poste','Niv.','Fatigue','État'],roster.map(p=>`<tr data-player="${p.id}"><td><b>${p.name}</b></td><td>${p.position}</td><td>${p.overall}</td><td>${Math.round(p.fatigue*100)}%</td><td>${p.injury|| (p.suspension_matches_remaining?'Suspendu':'Disponible')}</td></tr>`))}</article><article class="card side"><h2>Calendrier</h2>${table(['Date','Match','Résultat'],calendar.slice(0,8).map(m=>`<tr><td>${m.date}</td><td>${m.home_club_id===id?'Domicile':'Extérieur'}</td><td>${m.result?`${m.result.home_goals}–${m.result.away_goals}`:'—'}</td></tr>`))}</article></div>`;bindPlayers()}
async function player(id){const p=await api(`/joueurs/${id}`);title.textContent=p.name;app.innerHTML=`<div class="details"><article class="card"><p class="eyebrow">${p.position} · NIVEAU ${p.overall}</p><h2 class="panel-title">${p.name}</h2><p class="subtle">Fatigue ${Math.round(p.fatigue*100)}% · Forme ${p.form.toFixed(2)} · Moral ${p.morale.toFixed(2)}</p><h2>Attributs</h2>${Object.entries(p.attributes).map(([n,v])=>`<div class="attribute"><span>${n}</span><div class="bar"><i style="width:${v}%"></i></div><b>${v}</b></div>`).join('')}</article><article class="card"><h2>Saison en cours</h2>${table(['Matches','Buts','Tirs','Jaunes','Rouges'],[`<tr>${Object.values(p.season).map(v=>`<td><b>${v}</b></td>`).join('')}</tr>`])}</article></div>`}
async function match(id){const m=await api(`/matches/${id}`);title.textContent='Compte rendu';app.innerHTML=`<article class="card"><p class="eyebrow">JOURNÉE ${m.round} · ${m.date}</p><h2 class="panel-title">${clubName(m.home_club_id)} <span class="badge">${m.home_goals} – ${m.away_goals}</span> ${clubName(m.away_club_id)}</h2><h2>Événements</h2>${table(['Temps','Type','Joueur','Zone'],m.events.map(e=>`<tr><td>${e.second}s</td><td>${e.kind}</td><td>${e.primary_player_id}</td><td>${e.zone}</td></tr>`))}</article>`}
async function route(){try{const [view,id]=location.hash.slice(1).split('/');if(view==='competition')return competition(id);if(view==='club')return club(id);if(view==='player')return player(id);if(view==='match')return match(id);if(view==='clubs')return clubs();if(view==='joueurs')return players();if(view==='competitions')return competition(competitions[0].id);return dashboard()}catch(e){console.error(e);app.replaceChildren(document.querySelector('#error-template').content.cloneNode(true))}}
async function boot(){try{world=await api('/monde/etat');setWorld(world);competitions=await api('/competitions');const all=await api('/clubs');all.forEach(c=>clubCache.set(c.id,c.name));await route()}catch(e){app.replaceChildren(document.querySelector('#error-template').content.cloneNode(true))}}
document.querySelector('#advance-day').onclick=async()=>{setWorld(await api('/monde/avancer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jusqu_a:'jour'})}));route()};document.querySelector('#advance-round').onclick=async()=>{setWorld(await api('/monde/avancer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jusqu_a:'journee'})}));route()};window.addEventListener('hashchange',route);boot();
